### ISSUE TITLE
Return ArviZ output

### ISSUE THREAD

**Issue by eigenfoo** [eigenfoo/littlemcmc#59]
Instead of returning NumPy arrays and Python dicts as output, we should let there be an option to return the output as an ArviZ object. This would allow much better compatibility.

**Comment by eigenfoo** [comment]
Thinking about this a bit more: supporting this requires that littlemcmc know the names of the variables. This would probably look like optional lists of names, coordinates and dimensions that the user can pass to `lmc.sample`, which we would then use to do something like this: https://arviz-devs.github.io/arviz/notebooks/InferenceDataCookbook.html#From-dictionary-with-coords-and-dims

It's true that `chain` and `draw` are always coordinates, but beyond I'm not sure we can offer any more convenience to the user: they might just be better off converting it to ArviZ on their own.

I'm thinking of just not supporting this: any thoughts @dfm?

**Comment by dfm** [comment]
As long as we return a chain that has the right shape then I think it's fine to let users be responsible for the conversion. Perhaps we can just add an example to the docs. `emcee` also doesn't track variable names, so we could look at the `arviz.from_emcee` function for inspiration.

**Comment by eigenfoo** [comment]
Added a code snippet here: https://littlemcmc.readthedocs.io/en/latest/tutorials/framework_cookbook.html#visualize-traces-with-arviz

I actually think it's simple enough to PR to ArviZ... once we fix the glaring issues with littlemcmc, of course 😄
