### ISSUE TITLE
Support for discrete variables in Hamiltonian Monte Carlo sampler

### ISSUE THREAD

**Issue by zoj613** [eigenfoo/littlemcmc#79]
Ive read in the documentation that this library only supports continuous variables. Any thoughts on adding support for loglikelihood functions that have a mixture of continuous and discrete parameters? The following papers seem to be addressing how to build a sampler in such a case:
[Discontinuous Hamiltonian Monte Carlo for discrete parameters and discontinuous likelihoods](https://academic.oup.com/biomet/article/107/2/365/5799014)

[Continuous Relaxations for DiscreteHamiltonian Monte Carlo](https://papers.nips.cc/paper/4652-continuous-relaxations-for-discrete-hamiltonian-monte-carlo.pdf)

[Auxiliary-variable Exact Hamiltonian MonteCarlo Samplers for Binary Distributions](https://papers.nips.cc/paper/5045-auxiliary-variable-exact-hamiltonian-monte-carlo-samplers-for-binary-distributions.pdf)

**Comment by eigenfoo** [comment]
Hi!

I view discrete variables as outside the scope of this project. Users who want to sample discrete parameters should consider using PyMC3 instead which already supports [a bunch of discrete random variables](https://docs.pymc.io/api/distributions/discrete.html). This project is limited to merely exposing the HMC/NUTS sampler for use with an arbitrary Python callable as a logp/dlogp function.

Apologies if this wasn't clear in the README: I've written this up in the [littlemcmc docs](https://littlemcmc.readthedocs.io/en/latest/tutorials/quickstart.html#who-should-use-littlemcmc), but I should definitely point to that in the README. I'll close this issue now, but thanks for raising this!
